#! /bin/bash -ue
#
# ----------------------------------------------------------------------
#
# zingzong build script for win32/win64
#
# by Benjamin Gerard AKA Ben/OVR
#
# ----------------------------------------------------------------------

build=../zz_build

# Program name
prog=$(basename "$0" .sh)

# Basename of dirname is our host name
[ -n "${arch-}" ] ||
    export arch="${PWD##*/}"

case "$arch" in

    in_zingzong)
        #########################
        # Winamp plugin special #
        #########################
        export WADIR="$(regtool -W get /user/Software/Winamp/)"
	which cygpath >/dev/null 2>/dev/null && 
	    WADIR="$(cygpath -m "$WADIR")"
        set -- "$@" NO_AO=1 NO_SRATE=1
        export arch=i686-w64-mingw32
        export ZZ_MAKEFILE=../src/zz-winamp/Makefile
        ;;

    *-*-mingw*)
        ######################
        # Only support mingw #
        ######################
        ;;

    *) echo "$prog: not a valid host triplet -- $arch" >&2
       exit 1 ;;
esac

# ----------------------------------------------------------------------
# You can always set the benovr variable if you are trying to
# impersonate me. Or more seriously if you have soxr installed
# somewhere unconventional.

# Determine if that's me using my gpg footprint
if gpg -K | grep -c 52D4145B; then
    benovr="${HOME}/_Arch"     # that's where I store my builds
fi >/dev/null 2>/dev/null


# ----------------------------------------------------------------------
# Looking for soxr in here. For some reason my soxr build does not
# have a .pc so I have to set the SOXR_ variables manually.  This will
# set SOXR to the prefix where soxr has installed for this
# architecture.

if [ "${benovr}" ] && [ s${SOXR+et} != set ]; then

    set +f; shopt -s nullglob
    for dir in "${benovr}/${arch}"/soxr* "${benovr}/${arch}"/.; do
        if [ -r "${dir}"/include/soxr.h ]; then
            echo " * Found soxr.h in \"$dir\""
            SOXR="$dir"
        fi
    done

fi

if [ s${SOXR+et} = set ]; then

    # Set SOXR_LIBS if not already set
    if [ s${SOXR_LIBS+et} != set ]; then
        SOXR_LIBS="-L${SOXR}/lib -lsoxr"
    fi

    # Set SOXR_CFLAGS if not already set
    if [ s${SOXR_CFLAGS+et} != set ]; then
        SOXR_CFLAGS="-I${SOXR}/include"
    fi

fi

if [ "${SOXR_LIBS-}" ]; then

    NO_SOXR=0
    set -- \
        SOXR_CFLAGS="${SOXR_CFLAGS-}" \
        SOXR_LIBS="${SOXR_LIBS}" \
        NO_SOXR=0 \
        "$@"

fi

# ----------------------------------------------------------------------
# Let's build
# ----------------------------------------------------------------------

exec $build "$@"
